#on:
#  pull_request:
#    paths-ignore:
#      - '.github/**'
#      - '**.yml'
#      - '**.xml'
#      - 'LICENSE'
#      - '.gitignore'
#  push:
#    paths-ignore:
#      - '.github/**'
#      - '**.yml'
#      - '**.xml'
#      - 'LICENSE'
#      - '.gitignore'